export const queries = {
  critical: `query CriticalAnnouncement { result: criticalannouncement { id data { showMessage: campusmessageon title description url } } }`,
  weather: `query Weather { result: weatherfeed { id data { created location current { id weather weatherImage text temp startTime periodname } forecast { id iconLinks periodname friendlyDate startTime tempLabel temp text weather } } } }`,
  calendar: `query Calendar($calendarId: String!, $order: SortOrder, $timeMin: String, $timeMax: String, $maxResults: Int, $editAccess: Boolean, $timeWindow: String, $status: String) { result: googlecalfeed(calendarId: $calendarId, editAccess: $editAccess, order: $order, timeMin: $timeMin, timeMax: $timeMax, maxResults: $maxResults, timeWindow: $timeWindow, status: $status) { id calendarId calendarName data { id title description allday startdate enddate url updated status source } } }`,
  libcal: `query LibraryCalendar($calendarId: String!, $order: SortOrder, $timeMin: String, $timeMax: String, $maxResults: Int, $timeWindow: String, $status: String) { result: libcalfeed(calendarId: $calendarId, order: $order, timeMin: $timeMin, timeMax: $timeMax, maxResults: $maxResults, timeWindow: $timeWindow, status: $status) { id data { id title description allday startdate enddate status source } } }`,
  cbord: `query DiningMenu($calendarId: String!, $order: SortOrder, $timeMin: String, $timeMax: String, $maxResults: Int, $timeWindow: String) { result: cbordnetmenufeed(calendarId: $calendarId, order: $order, timeMin: $timeMin, timeMax: $timeMax, maxResults: $maxResults, timeWindow: $timeWindow) { id calendarId calendarName data { id title description allday startdate enddate url updated status } } }`,
  news: `query CampusNews($feedUrls: [String!]!, $feedStickyUrls: [String!]!, $maxResults: Int, $prevDaysToQuery: Int) { result: combinedrssnewsfeeds(feedUrls: $feedUrls, feedStickyUrls: $feedStickyUrls, maxResults: $maxResults, prevDaysToQuery: $prevDaysToQuery) { id data { id title description url source published sticky } } }`,
  events: `query CampusEvents($currentOnly: Boolean, $days: Int) { result: swatcentralfeed(currentOnly: $currentOnly, days: $days) { id data { title id url eventactionurl description startdate enddate allday eventtype formatteddate location organization } } }`,
  transit: `query Transit($departureStation: String!, $arrivalStation: String!, $maxResults: Int) { result: septatrainfeed(departureStation: $departureStation, arrivalStation: $arrivalStation, maxResults: $maxResults) { id data { id orig_train orig_line orig_departure_time orig_delay } } }`,
  sports: `query Sports($count: Int) { result: sportsscoresfeed(count: $count) { id data { id date is_today sport_title opponent opponent_image gender location_indicator conference conference_logo location result team_score opponent_score story_title story_url story_image boxscore_url schedule promotion_name livestream_url tournament stats_url } } }`,
  mindCandy: `query MindCandy($maxResults: Int, $drupalId: String, $resourceVersion: Int) { result: mindcandyfeed(maxResults: $maxResults, drupalId: $drupalId, resourceVersion: $resourceVersion) { id data { id paragraphType title mcImageUrl mcImageAlt mcAbstractText mcLink mcLinkTitle revealedText mcTheme correctRevision } } }`,
} as const;
